feat: add Ant Design and emotion
rising-pixels/budget-planner pull request #14
Opened 2023-05-13 11:59 UTC by Kubenz98

Closes (#8)

2023-05-16 19:34 UTC, awinnicki requested changes

2023-05-16 19:34 UTC, awinnicki commented on src/pages/_app.tsx
> +declare module "@emotion/react" {
Wynieś proszę tę deklarację do osobnego pliku `types/emotion.d.ts`. Dobrze jest deklaracje typów trzymać w oddzielnych plikach.

2023-05-16 19:34 UTC, awinnicki commented on tsconfig.json
> +    "types": ["@emotion/react/types/css-prop"],
Czy to wciąż do czegoś potrzebujemy?

2023-05-16 19:34 UTC, awinnicki commented on src/pages/index.tsx
> +const { Text } = Typography;
Dodaj proszę linię odstępu po tej linii.

2023-05-16 19:34 UTC, awinnicki commented on src/pages/index.tsx
> +`;
Dodaj proszę linię odstępu po tej linii.

2023-05-16 19:34 UTC, awinnicki commented on tsconfig.json
> +, "src/pages/index.tsx"  ],
Czy to również do czegoś potrzebujemy?

2023-05-17 09:34 UTC, Kubenz98 commented on src/pages/_app.tsx
> +declare module "@emotion/react" {
Dodano plik emotion.d.ts

2023-05-17 09:35 UTC, Kubenz98 commented on src/pages/index.tsx
> +const { Text } = Typography;
Zrobione.

2023-05-17 09:35 UTC, Kubenz98 commented on src/pages/index.tsx
> +`;
Zrobione.

2023-05-17 09:35 UTC, Kubenz98 commented on tsconfig.json
> +, "src/pages/index.tsx"  ],
Nie, usunięte.

2023-05-17 13:44 UTC, awinnicki approved these changes

2023-05-17 15:10 UTC, merged