Eslint
rising-pixels/budget-planner pull request #19
Opened 2023-05-18 13:16 UTC by LalaSimon

Closes 18

2023-05-18 21:19 UTC, awinnicki requested changes

2023-05-18 21:19 UTC, awinnicki commented on package-lock.json
Wkradł się `package-lock.json` :D Do usunięcia.

2023-05-18 21:19 UTC, awinnicki commented on .eslintrc.json
> +      "files": ["./src/pages/index.tsx", "./src/pages/_app.tsx"],
Fajny pomysł z ustawieniem tego z poziomu konfiga, ale proponuję wyłączyć tę zasadę inlinowo w poszczególnych plikach, tak jak w tym przykładzie:

```tsx
// FIle /src/index.tsx

// eslint-disable-next-line import/no-default-export
export default HomePage;
```

Może się zdarzyć, że jednak coś będziemy eksportować dodatkowo z tych plików i wtedy będziemy chcieli już zastosować named exporty.

2023-05-18 21:19 UTC, awinnicki commented on package.json
> +    "eslint-config-prettier": "^8.8.0",
Ta paczka używana jest tylko podczas developmentu, więc lepiej przenieść ją do `devDependecies`.

2023-05-18 21:19 UTC, awinnicki commented on package.json
> +    "eslint-plugin-prettier": "^4.2.1",
Tak samo jak poprzednio, lepiej przenieść paczkę do `devDependecies`.

2023-05-18 21:21 UTC, awinnicki commented
@LalaSimon brakuje hashtagu w opisie PR'ki, więc nie stworzy się połączenie z zadaniem. Zaktualizuj proszę opis.

2023-05-19 06:53 UTC, LalaSimon commented
@awinnicki Wszystko poprawione i wypchnięte :)

2023-05-26 18:07 UTC, awinnicki approved these changes

2023-05-26 18:27 UTC, merged