feat: add functions for managing categories in the database
rising-pixels/budget-planner pull request #21
Opened 2023-05-24 13:47 UTC by Kubenz98

Closes #20

2023-05-25 15:46 UTC, sigo commented on src/pages/index.tsx
> +    this.version(2).stores({
Nie jestem pewien czy dokładnie rozumiem cel, potrzebę i zachowanie wersjonowania bazy danych. Czy mógłbyś mi to przybliżyć?

2023-05-25 15:47 UTC, sigo commented on src/pages/index.tsx
> +      categories: "uuid, name",
Czy to jedyny sposób zapisu? Wydaje się dosyć błędo-genny. To tylko stringi separowane przecinkiem.

2023-05-25 15:49 UTC, sigo commented on src/services/helpers/categoryExists.ts
> +};
https://stackoverflow.com/questions/53471147/should-i-worry-about-uuid-uniqueness

2023-05-25 15:50 UTC, sigo commented on src/services/indexedDBService.ts
To jest świetny przykład - te funkcje zdecydowanie warto podzielić na pliki.

2023-05-25 15:52 UTC, sigo requested changes
W ramach tego PR powinna powstać pierwsza prawdziwa domena - `categories`. I tam powinny trafić wszystkie utilsy, helpery, typy, funkcje itp.

2023-05-25 17:36 UTC, Kubenz98 commented on src/pages/index.tsx
> +    this.version(2).stores({
Z tego co się zorientowałem, to po dodaniu nowej tabeli (kategorie) dobrze jest zmienić numer wersji, aby użytkownik który ma zapisaną starą bazę danych w przeglądarce (bez nowej tabeli), mógł bez problemu korzystać z nowych funkcji.

2023-05-25 18:23 UTC, Kubenz98 commented on src/pages/index.tsx
> +      categories: "uuid, name",
Taki jest interfejs Version:

`export interface Version {
	stores(schema: {
		[tableName: string]: string | null;
	}): Version;
	upgrade(fn: (trans: Transaction) => PromiseLike<any> | void): Version;
}`

[https://dexie.org/docs/Version/Version.stores()](url)

Innego sposobu nie dostrzegam.

2023-05-25 18:32 UTC, Kubenz98 commented on src/services/helpers/categoryExists.ts
> +};
W commicie zostanie dodana unikalność uuid, w innym przypadku baza danych odrzuci kategorię.

2023-05-25 18:58 UTC, Kubenz98 commented on src/services/indexedDBService.ts
Podzielone.

2023-05-25 19:05 UTC, sigo commented on src/pages/index.tsx
> +    this.version(2).stores({
Jestem właśnie ciekaw jak zachowa się stara (istniejąca) struktura względem nowej. Czytałeś na ten temat?

2023-05-25 19:11 UTC, sigo commented on src/services/helpers/categoryExists.ts
> +};
Być może powinienem dokładnie opisać co mam na myśli. Przestrzeń identyfikatorów UUID jest tak ogromna, że co do zasady nie trzeba martwić się sprawdzaniem jej unikalności. A wtedy wskazana funkcja wydaje się zbędna.

Ale po dłuższym zastanowieniu - unikalność nie wyklucza sprawdzania istnienia danego UUID. Tutaj potrzebowałbym opinii @awinnicki.

2023-05-25 19:14 UTC, sigo commented on src/services/indexedDBService.ts
Nie opisałem tego, ale przywykłem do podziału na domeny już od głównego poziomu pod `src`. Czyli `modules` wydaje się zbędne. Nie wiem czy jego nazwa nie wprowadza też w zastanowienie, czym jest "moduł".

@awinnicki co sądzisz?

2023-05-25 19:16 UTC, Kubenz98 commented on src/pages/index.tsx
> +    this.version(2).stores({
Na tę chwilę mogę napisać, że indeksy mogą nie działać. Mogą być błędy z wartością w indeksie lub nieprawidłowe działanie zapytań, które z nich będą korzystały.
Upewnię się jutro i odniosę się do tego.

2023-05-26 09:25 UTC, Kubenz98 commented on src/services/helpers/categoryExists.ts
> +};
Zapomniałem do czego ta funkcja służy. Służy ona do zwrócenia false, gdy chcemy usunąć kategorię, której UUID nie istnieje. Wtedy rzucany jest błąd w bloku try catch.

Stworzona odnośnie przestrogi: `Funkcja usuwająca zwracać błąd, gdy wskazywana kategoria nie istnieje.`

2023-05-26 09:39 UTC, Kubenz98 commented on src/pages/index.tsx
> +    this.version(2).stores({
W docsach od Dexie krótko wspominają to co wyżej napisałem, że zapytania mogą nieprawidłowo działać, jeśli dodamy nowe tabele, a nie zmienimy wersji bazy danych.

https://dexie.org/docs/Tutorial/Design#database-versioning

2023-05-26 18:36 UTC, awinnicki commented on src/services/helpers/categoryExists.ts
> +};
Moim zdaniem nie powinniśmy się tym martwić i nie musimy sprawdzać czy ID już istnieje, ponieważ tak jak Mateusz wspomina, UUID co do zasady powinno być unikalne. Szansa, że UUID zostanie powtórzone jest praktycznie zerowa.

2023-05-26 18:38 UTC, awinnicki commented on src/services/indexedDBService.ts
Też przywykłem do bardziej płaskiej struktury folderów. Jak już to celowałbym bardziej w nazwę `domains`, która dla mnie jest bardziej wymowna niż `modules`, która jest mocno generyczna.

2023-05-26 20:01 UTC, awinnicki requested changes

2023-05-27 07:17 UTC, Kubenz98 commented on src/modules/categories/helpers/categoryExists.ts
> +  return !!categories.some(
Faktycznie, mój błąd, żyłem w przekonaniu, że zwraca wartość truthy.

2023-05-27 07:19 UTC, Kubenz98 commented on src/modules/categories/services/addCategoryService.ts
Nazwy plików zostały zmienione.

2023-05-27 07:20 UTC, Kubenz98 commented on src/services/indexedDBService.ts
Struktura folderów zmieniona.

2023-05-27 10:39 UTC, Kubenz98 commented on src/modules/categories/services/addCategoryService.ts
> +    const category = { uuid: uuidv4(), name };
trim() dodane.

2023-05-28 06:32 UTC, awinnicki commented on src/services/helpers/categoryExists.ts
> +};
@Kubenz98 usuń proszę funkcję `categoryUuidExists`, ponieważ nie jest już nigdzie używana.

2023-05-28 07:21 UTC, awinnicki requested changes
.

2023-05-28 07:21 UTC, awinnicki commented on src/categories/services/addCategory.ts
> +  return db.categories.add(category).catch();
`.catch()` pozostało chyba przez przypadek? 🤔

2023-05-28 07:21 UTC, awinnicki commented on src/services/helpers/categoryExists.ts
> +};
Pomyłka, funkcja jest używana, ale myślę, że doszliśmy do wniosku, że nie ma potrzeby sprawdzania powtarzalności UUID. Usuń proszę sprawdzanie ID w `deleteCategory` i samą w sobie definicję funkcji `categoryUuidExists`.

2023-05-28 07:21 UTC, awinnicki commented on src/categories/services/changeCategoryName.ts
> +  }
Dla lepszej czytelności proponuję dodać poniżej pustą linię.

2023-05-28 07:21 UTC, awinnicki commented on src/categories/services/addCategory.ts
> +  }
Dla lepszej czytelności proponuję dodać poniżej pustą linię.

2023-05-28 07:21 UTC, awinnicki requested changes
const existingCategories = await db.categories.toArray();
  if (categoryNameExists(existingCategories, name)) {
    throw new Error("This category exists!");
  }

2023-05-28 08:09 UTC, awinnicki commented on src/services/helpers/categoryExists.ts
> +};
> Ale po dłuższym zastanowieniu - unikalność nie wyklucza sprawdzania istnienia danego UUID. Tutaj potrzebowałbym opinii @awinnicki.

O rany, zakręciłem się. O czym innym całkiem pisałem, sorki moje niedopatrzenie.

Podsumowując, wydaje mi się, że sprawdzenie istnienia jest git.

2023-05-28 09:00 UTC, Kubenz98 commented on src/services/helpers/categoryExists.ts
> +};
Funkcja usunięta.

2023-05-28 09:01 UTC, Kubenz98 commented on src/categories/services/addCategory.ts
> +
Linia usunięta.

2023-05-28 09:01 UTC, Kubenz98 commented on src/categories/helpers/categoryExists.ts
Nazwa folderu zmieniona.

2023-05-28 09:01 UTC, Kubenz98 commented on src/categories/services/addCategory.ts
> +  return db.categories.add(category).catch();
Dokładnie tak było, niedopatrzenie ;)

2023-05-28 09:01 UTC, Kubenz98 commented on src/categories/services/changeCategoryName.ts
> +  }
Linia dodana.

2023-05-28 09:02 UTC, Kubenz98 commented on src/categories/services/addCategory.ts
> +  }
Linia dodana.

2023-06-02 17:30 UTC, sigo requested changes

2023-06-02 17:30 UTC, sigo commented on src/categories/services/addCategory.ts
> +  const category = { uuid: uuidv4(), name: name.trim() };
Dostrzegam tu potencjalną dziurę. `trim` wykonywany jest po sprawdzeniu zajętości nazwy w bazie. Powinno to przechodzić przez uporządkowany linearny proces.

1. `trim`.
2. Weryfikacja zajętości.
3. Dodawanie kategorii lub rzucanie błędem.

Oczywiście należałoby to zmienić w analogicznych miejscach.

2023-06-05 12:29 UTC, Kubenz98 commented on src/pages/index.tsx
> +      categories: "&uuid, name",
Nazwa kolumny zmieniona.

2023-06-06 17:37 UTC, merged